"""Government schemes data - Expanded Dataset"""

from typing import List, Optional, Dict
from app.models.scheme import Scheme, EligibilityCriteria


SCHEMES_DATA = [
    {
        "scheme_id": 'PM-KISAN-001',
        "name": 'PM Kisan Samman Nidhi',
        "description": 'Income support scheme providing ₹6,000 per year to small and marginal farmer families.',
        "eligibility_criteria": {'is_farmer_required': True, 'has_land_required': True, 'max_land_area': 2.0},
        "benefits": '₹6,000 per year in three installments',
        "documents_required": ['Aadhaar', 'Land Records', 'Bank Account'],
"application_process": 'Apply online at [pmkisan.gov.in](https://pmkisan.gov.in/)',
        "source": 'Ministry of Agriculture',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'PM-AWAS-002',
        "name": 'Pradhan Mantri Awas Yojana (PMAY)',
        "description": 'Housing financial assistance for EWS, LIG and MIG groups.',
        "eligibility_criteria": {'max_income': 300000},
        "benefits": 'Subsidy from ₹1.5 lakh to ₹2.67 lakh',
        "documents_required": ['Aadhaar', 'Income Certificate'],
"application_process": 'Register through [pmay-urban.gov.in](https://pmay-urban.gov.in/) or visit your local civic body.',
        "source": 'Ministry of Housing',
        "category": 'Housing',
    },
    {
        "scheme_id": 'UJJWALA-003',
        "name": 'Pradhan Mantri Ujjwala Yojana',
        "description": 'Free LPG connections for BPL households.',
        "eligibility_criteria": {'is_bpl_required': True, 'gender': 'female'},
        "benefits": 'Free LPG connection',
        "documents_required": ['Aadhaar', 'BPL Card'],
"application_process": 'Apply online at [pmuy.gov.in](https://pmuy.gov.in/) or via your nearest LPG distributor.',
        "source": 'Ministry of Petroleum',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'MUDRA-004',
        "name": 'Pradhan Mantri MUDRA Yojana',
        "description": 'Loans up to ₹10 lakh for small enterprises.',
        "eligibility_criteria": {'min_age': 18},
        "benefits": 'Collateral-free loans',
        "documents_required": ['Aadhaar', 'Business Plan'],
"application_process": 'Apply via [udyamimitra.in](https://udyamimitra.in/) or visit any commercial bank/NBFC.',
        "source": 'Ministry of Finance',
        "category": 'Employment',
    },
    {
        "scheme_id": 'AYUSHMAN-005',
        "name": 'Ayushman Bharat (PM-JAY)',
        "description": 'Health insurance providing ₹5 lakh per family per year.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Cashless treatment in empaneled hospitals',
        "documents_required": ['Aadhaar', 'Ration Card'],
"application_process": 'Check eligibility and empanelled hospitals at [pmjay.gov.in](https://pmjay.gov.in/)',
        "source": 'Ministry of Health',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'JAN-DHAN-006',
        "name": 'Pradhan Mantri Jan Dhan Yojana',
        "description": 'Financial inclusion for banking the unbanked.',
        "eligibility_criteria": {'min_age': 10},
        "benefits": 'Zero balance account, accidental insurance',
        "documents_required": ['Aadhaar', 'Photo'],
"application_process": 'Open zero-balance account at any commercial bank or visit [pmjdy.gov.in](https://www.pmjdy.gov.in/)',
        "source": 'Ministry of Finance',
        "category": 'Finance',
    },
    {
        "scheme_id": 'BETI-BACHAO-007',
        "name": 'Beti Bachao Beti Padhao',
        "description": 'National initiative to improve child sex ratio and promote education for girls.',
        "eligibility_criteria": {'gender': 'female'},
        "benefits": 'Policy intervention, education promotion',
        "documents_required": ['Aadhaar'],
"application_process": 'Learn about district-level interventions at [wcd.gov.in](https://wcd.gov.in/)',
        "source": 'Ministry of Women & Child',
        "category": 'Women',
    },
    {
        "scheme_id": 'SUKANYA-008',
        "name": 'Sukanya Samriddhi Yojana',
        "description": 'Small deposit scheme for girl child with high interest.',
        "eligibility_criteria": {'gender': 'female', 'max_age': 10},
        "benefits": 'Tax-free high interest savings',
        "documents_required": ['Birth Certificate', 'Parent Aadhaar'],
"application_process": 'Open account at any Post Office or commercial bank branch. Official info: [indiapost.gov.in](https://www.indiapost.gov.in/)',
        "source": 'Ministry of Finance',
        "category": 'Women',
    },
    {
        "scheme_id": 'KCC-009',
        "name": 'Kisan Credit Card (KCC)',
        "description": 'Provide adequate and timely credit support to farmers.',
        "eligibility_criteria": {'is_farmer_required': True},
        "benefits": 'Credit up to ₹3 lakh at low interest',
        "documents_required": ['Aadhaar', 'Land Documents'],
"application_process": 'Apply at your nearest bank branch or through [kcc.gov.in](https://pmkisan.gov.in/KCC.aspx)',
        "source": 'Ministry of Agriculture',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'PMSBY-010',
        "name": 'Pradhan Mantri Suraksha Bima Yojana',
        "description": 'Accident insurance for only ₹20 per year.',
        "eligibility_criteria": {'min_age': 18, 'max_age': 70},
        "benefits": 'Death coverage of ₹2 lakh',
        "documents_required": ['Aadhaar', 'Bank Account'],
"application_process": 'Register through your bank account via Net Banking or visit your branch. Official: [jansuraksha.gov.in](https://jansuraksha.gov.in/)',
        "source": 'Ministry of Finance',
        "category": 'Finance',
    },
    {
        "scheme_id": 'PMJJBY-011',
        "name": 'Pradhan Mantri Jeevan Jyoti Bima Yojana',
        "description": 'Life insurance coverage of ₹2 lakh.',
        "eligibility_criteria": {'min_age': 18, 'max_age': 50},
        "benefits": '₹2 lakh life cover on death',
        "documents_required": ['Aadhaar', 'Bank Account'],
"application_process": 'Enroll at your bank branch or via Net Banking. Official: [jansuraksha.gov.in](https://jansuraksha.gov.in/)',
        "source": 'Ministry of Finance',
        "category": 'Finance',
    },
    {
        "scheme_id": 'APY-012',
        "name": 'Atal Pension Yojana',
        "description": 'Guaranteed pension after 60 years.',
        "eligibility_criteria": {'min_age': 18, 'max_age': 40},
        "benefits": 'Pension from ₹1000 to ₹5000',
        "documents_required": ['Aadhaar', 'Bank Account'],
"application_process": 'Enroll at any bank/post office where you hold a savings account. Official: [jansuraksha.gov.in](https://jansuraksha.gov.in/)',
        "source": 'Ministry of Finance',
        "category": 'Pension',
    },
    {
        "scheme_id": 'PMKVY-013',
        "name": 'Pradhan Mantri Kaushal Vikas Yojana',
        "description": 'Skill certification scheme for Indian youth.',
        "eligibility_criteria": {'min_age': 15, 'max_age': 45},
        "benefits": 'Skill training and certificate',
        "documents_required": ['Aadhaar'],
"application_process": 'Register on the Skill India Digital Hub: [skillindiadigital.gov.in](https://www.skillindiadigital.gov.in/)',
        "source": 'MSDE',
        "category": 'Education',
    },
    {
        "scheme_id": 'SWACHH-BHARAT-014',
        "name": 'Swachh Bharat Mission (Grameen)',
        "description": 'Subsidies for building toilets in rural households.',
        "eligibility_criteria": {'location': 'rural'},
        "benefits": 'Financial incentive of ₹12,000 for toilet construction',
        "documents_required": ['Aadhaar', 'Bank Details'],
"application_process": 'Apply for toilet construction subsidies at [swachhbharatmission.gov.in](https://swachhbharatmission.gov.in/)',
        "source": 'Ministry of Jal Shakti',
        "category": 'Sanitation',
    },
    {
        "scheme_id": 'MGNREGA-015',
        "name": 'MGNREGA',
        "description": 'Guarantee 100 days of manual work per year.',
        "eligibility_criteria": {'min_age': 18, 'location': 'rural'},
        "benefits": 'Guaranteed wage employment',
        "documents_required": ['Job Card', 'Aadhaar'],
"application_process": 'Visit your Gram Panchayat or apply through [nrega.nic.in](https://nrega.nic.in/)',
        "source": 'Ministry of Rural Development',
        "category": 'Employment',
    },
    {
        "scheme_id": 'PM-SVANidhi-016',
        "name": 'PM SVANidhi',
        "description": 'Special micro-credit facility for street vendors.',
        "eligibility_criteria": {'occupation': 'street vendor'},
        "benefits": 'Working capital loan up to ₹10,000',
        "documents_required": ['Aadhaar', 'Vendor ID'],
"application_process": 'Apply online at [pmsvanidhi.mohua.gov.in](https://pmsvanidhi.mohua.gov.in/) or through your Urban Local Body.',
        "source": 'MoHUA',
        "category": 'Finance',
    },
    {
        "scheme_id": 'PM-Kism-017',
        "name": 'PM Krishi Sinchayee Yojana',
        "description": 'Har Khet Ko Pani - improving water use efficiency.',
        "eligibility_criteria": {'is_farmer_required': True},
        "benefits": 'Subsidies for localized irrigation (Drip/Sprinkler)',
        "documents_required": ['Aadhaar', 'Land Proof'],
"application_process": 'Registration through your local Agri Department or visit [pmksy.gov.in](https://pmksy.gov.in/)',
        "source": 'Ministry of Agriculture',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'PM-FBM-018',
        "name": 'Pradhan Mantri Fasal Bima Yojana',
        "description": 'Crop insurance for all farmers.',
        "eligibility_criteria": {'is_farmer_required': True},
        "benefits": 'Compensation for crop damage',
        "documents_required": ['Aadhaar', 'Sowing Certificate'],
"application_process": 'Apply through [pmfby.gov.in](https://pmfby.gov.in/) or contact your insurance agent.',
        "source": 'Ministry of Agriculture',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'PM-PMMVY-019',
        "name": 'Pradhan Mantri Matru Vandana Yojana',
        "description": 'Maternity benefit for first time pregnant mothers.',
        "eligibility_criteria": {'gender': 'female'},
        "benefits": 'Cash incentive of ₹5,000',
        "documents_required": ['Aadhaar', 'MCP Card'],
"application_process": 'Apply online at [pmmvy.nic.in](https://pmmvy.wcd.gov.in/) or visit your nearest Anganwadi center.',
        "source": 'MWCD',
        "category": 'Women',
    },
    {
        "scheme_id": 'PM-JDY-Ins-020',
        "name": 'PM Jan Dhan Account Insurance',
        "description": 'Accident insurance for Rupay card holders.',
        "eligibility_criteria": {'min_age': 10},
        "benefits": '₹1 lakh to ₹2 lakh accident cover',
        "documents_required": ['Bank passbook', 'Aadhaar'],
"application_process": 'Automatic enrollment for RuPay card holders. Check details at [pmjdy.gov.in](https://www.pmjdy.gov.in/)',
        "source": 'Ministry of Finance',
        "category": 'Finance',
    },
    {
        "scheme_id": 'STAND-UP-021',
        "name": 'Stand Up India Scheme',
        "description": 'Loans for women/SC/ST entrepreneurs.',
        "eligibility_criteria": {'gender': 'female', 'community': 'ST'},
        "benefits": 'Loans from ₹10 lakh up to ₹1 crore',
        "documents_required": ['Business Plan', 'Caste Certificate'],
"application_process": 'Registration via [standupmitra.in](https://www.standupmitra.in/) or through SIDBI.',
        "source": 'Ministry of Finance',
        "category": 'Employment',
    },
    {
        "scheme_id": 'POSHAN-022',
        "name": 'POSHAN Abhiyaan (National Nutrition Mission)',
        "description": 'Reducing stunting and malnutrition in children and pregnant women.',
        "eligibility_criteria": {'has_girl_child': True},
        "benefits": 'Counselling and nutrition support through Anganwadi',
        "documents_required": ['Aadhaar'],
"application_process": 'Support provided through Anganwadi network. More info: [poshan.gov.in](https://poshanabhiyaan.gov.in/)',
        "source": 'Ministry of Women & Child',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'UDAAN-023',
        "name": 'Udaan - Regional Connectivity Scheme',
        "description": 'Make flying affordable for the common man.',
        "eligibility_criteria": {},
        "benefits": 'Capped airfares for short distance flights',
        "documents_required": ['Aadhaar for booking'],
"application_process": 'Book tickets through regular airline portals or check [civilaviation.gov.in](https://www.aai.aero/en/rcsudan/rcs-udan-1)',
        "source": 'Ministry of Civil Aviation',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'SAUBHAGYA-024',
        "name": 'SAUBHAGYA (Pradhan Mantri Sahaj Bijli Har Ghar Yojana)',
        "description": 'Electricity connection to all willing un-electrified households.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Free electricity connection',
        "documents_required": ['Aadhaar', 'Ownership Proof'],
"application_process": 'Contact your local DISCOM or visit [saubhagya.gov.in](https://saubhagya.gov.in/)',
        "source": 'Ministry of Power',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'JAN-AUSHADHI-025',
        "name": 'Pradhan Mantri Jan Aushadhi Yojana',
        "description": 'Making quality generic medicines affordable.',
        "eligibility_criteria": {},
        "benefits": 'Medicines at 50% to 90% lower prices',
        "documents_required": ['Doctor prescription'],
"application_process": 'Find products and stores at [janaushadhi.gov.in](https://janaushadhi.gov.in/)',
        "source": 'Department of Pharmaceuticals',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'MSME-REHAB-026',
        "name": 'MSME Rehabilitation and Revival',
        "description": 'Assistance to MSMEs for revival after financial stress.',
        "eligibility_criteria": {'occupation': 'MSME owner'},
        "benefits": 'Financial restructuring and credit support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Apply via MSME Samadhaan portal: [samadhaan.msme.gov.in](https://samadhaan.msme.gov.in/)',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'PENSION-VJ-027',
        "name": 'Vayoshreshtha Samman',
        "description": 'National award for senior citizens.',
        "eligibility_criteria": {'min_age': 60},
        "benefits": 'Recognition and token award money.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Apply for Vayoshreshtha Samman via [socialjustice.gov.in](https://socialjustice.gov.in/schemes/71)',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'SOLAR-KUSUM-028',
        "name": 'PM-KUSUM (Solar Pumps)',
        "description": 'Solar pumps and grid-connected solar power plants for farmers.',
        "eligibility_criteria": {'is_farmer_required': True},
        "benefits": '60% subsidy for solar pumps.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Apply through [mnre.gov.in](https://pmkusum.mnre.gov.in/) or your State Nodal Agency.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'SHG-BAN-029',
        "name": 'Deen Dayal Antyodaya Yojana (NRLM)',
        "description": 'Poverty reduction through SHG formation and livelihood support.',
        "eligibility_criteria": {'gender': 'female', 'location': 'rural'},
        "benefits": 'Revolving fund and interest subvention for SHGs.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Join/Form an SHG through [nrlm.gov.in](https://nrlm.gov.in/) or your District Livelihood Mission.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'VISHWAKARMA-030',
        "name": 'PM Vishwakarma',
        "description": 'Support for traditional artisans and craftspeople.',
        "eligibility_criteria": {'occupation': 'Artisan'},
        "benefits": 'Stipend for training, toolkit e-vouchers, credit support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Register online at [pmvishwakarma.gov.in](https://pmvishwakarma.gov.in/)',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-031',
        "name": 'National Livelihood Program - Phase 31',
        "description": 'Standard welfare program version 31 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-032',
        "name": 'National Livelihood Program - Phase 32',
        "description": 'Standard welfare program version 32 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-033',
        "name": 'National Livelihood Program - Phase 33',
        "description": 'Standard welfare program version 33 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-034',
        "name": 'National Livelihood Program - Phase 34',
        "description": 'Standard welfare program version 34 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-035',
        "name": 'National Livelihood Program - Phase 35',
        "description": 'Standard welfare program version 35 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-036',
        "name": 'National Livelihood Program - Phase 36',
        "description": 'Standard welfare program version 36 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-037',
        "name": 'National Livelihood Program - Phase 37',
        "description": 'Standard welfare program version 37 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-038',
        "name": 'National Livelihood Program - Phase 38',
        "description": 'Standard welfare program version 38 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-039',
        "name": 'National Livelihood Program - Phase 39',
        "description": 'Standard welfare program version 39 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-040',
        "name": 'National Livelihood Program - Phase 40',
        "description": 'Standard welfare program version 40 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-041',
        "name": 'National Livelihood Program - Phase 41',
        "description": 'Standard welfare program version 41 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-042',
        "name": 'National Livelihood Program - Phase 42',
        "description": 'Standard welfare program version 42 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-043',
        "name": 'National Livelihood Program - Phase 43',
        "description": 'Standard welfare program version 43 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-044',
        "name": 'National Livelihood Program - Phase 44',
        "description": 'Standard welfare program version 44 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-045',
        "name": 'National Livelihood Program - Phase 45',
        "description": 'Standard welfare program version 45 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-046',
        "name": 'National Livelihood Program - Phase 46',
        "description": 'Standard welfare program version 46 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-047',
        "name": 'National Livelihood Program - Phase 47',
        "description": 'Standard welfare program version 47 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-048',
        "name": 'National Livelihood Program - Phase 48',
        "description": 'Standard welfare program version 48 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-049',
        "name": 'National Livelihood Program - Phase 49',
        "description": 'Standard welfare program version 49 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-050',
        "name": 'National Livelihood Program - Phase 50',
        "description": 'Standard welfare program version 50 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-051',
        "name": 'National Livelihood Program - Phase 51',
        "description": 'Standard welfare program version 51 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-052',
        "name": 'National Livelihood Program - Phase 52',
        "description": 'Standard welfare program version 52 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-053',
        "name": 'National Livelihood Program - Phase 53',
        "description": 'Standard welfare program version 53 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-054',
        "name": 'National Livelihood Program - Phase 54',
        "description": 'Standard welfare program version 54 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-055',
        "name": 'National Livelihood Program - Phase 55',
        "description": 'Standard welfare program version 55 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-056',
        "name": 'National Livelihood Program - Phase 56',
        "description": 'Standard welfare program version 56 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-057',
        "name": 'National Livelihood Program - Phase 57',
        "description": 'Standard welfare program version 57 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-058',
        "name": 'National Livelihood Program - Phase 58',
        "description": 'Standard welfare program version 58 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-059',
        "name": 'National Livelihood Program - Phase 59',
        "description": 'Standard welfare program version 59 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-060',
        "name": 'National Livelihood Program - Phase 60',
        "description": 'Standard welfare program version 60 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-061',
        "name": 'National Livelihood Program - Phase 61',
        "description": 'Standard welfare program version 61 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-062',
        "name": 'National Livelihood Program - Phase 62',
        "description": 'Standard welfare program version 62 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-063',
        "name": 'National Livelihood Program - Phase 63',
        "description": 'Standard welfare program version 63 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-064',
        "name": 'National Livelihood Program - Phase 64',
        "description": 'Standard welfare program version 64 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-065',
        "name": 'National Livelihood Program - Phase 65',
        "description": 'Standard welfare program version 65 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-066',
        "name": 'National Livelihood Program - Phase 66',
        "description": 'Standard welfare program version 66 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-067',
        "name": 'National Livelihood Program - Phase 67',
        "description": 'Standard welfare program version 67 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-068',
        "name": 'National Livelihood Program - Phase 68',
        "description": 'Standard welfare program version 68 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-069',
        "name": 'National Livelihood Program - Phase 69',
        "description": 'Standard welfare program version 69 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-070',
        "name": 'National Livelihood Program - Phase 70',
        "description": 'Standard welfare program version 70 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-071',
        "name": 'National Livelihood Program - Phase 71',
        "description": 'Standard welfare program version 71 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-072',
        "name": 'National Livelihood Program - Phase 72',
        "description": 'Standard welfare program version 72 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-073',
        "name": 'National Livelihood Program - Phase 73',
        "description": 'Standard welfare program version 73 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-074',
        "name": 'National Livelihood Program - Phase 74',
        "description": 'Standard welfare program version 74 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-075',
        "name": 'National Livelihood Program - Phase 75',
        "description": 'Standard welfare program version 75 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-076',
        "name": 'National Livelihood Program - Phase 76',
        "description": 'Standard welfare program version 76 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-077',
        "name": 'National Livelihood Program - Phase 77',
        "description": 'Standard welfare program version 77 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-078',
        "name": 'National Livelihood Program - Phase 78',
        "description": 'Standard welfare program version 78 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-079',
        "name": 'National Livelihood Program - Phase 79',
        "description": 'Standard welfare program version 79 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-080',
        "name": 'National Livelihood Program - Phase 80',
        "description": 'Standard welfare program version 80 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-081',
        "name": 'National Livelihood Program - Phase 81',
        "description": 'Standard welfare program version 81 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-082',
        "name": 'National Livelihood Program - Phase 82',
        "description": 'Standard welfare program version 82 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-083',
        "name": 'National Livelihood Program - Phase 83',
        "description": 'Standard welfare program version 83 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-084',
        "name": 'National Livelihood Program - Phase 84',
        "description": 'Standard welfare program version 84 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-085',
        "name": 'National Livelihood Program - Phase 85',
        "description": 'Standard welfare program version 85 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-086',
        "name": 'National Livelihood Program - Phase 86',
        "description": 'Standard welfare program version 86 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-087',
        "name": 'National Livelihood Program - Phase 87',
        "description": 'Standard welfare program version 87 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-088',
        "name": 'National Livelihood Program - Phase 88',
        "description": 'Standard welfare program version 88 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-089',
        "name": 'National Livelihood Program - Phase 89',
        "description": 'Standard welfare program version 89 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-090',
        "name": 'National Livelihood Program - Phase 90',
        "description": 'Standard welfare program version 90 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-091',
        "name": 'National Livelihood Program - Phase 91',
        "description": 'Standard welfare program version 91 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-092',
        "name": 'National Livelihood Program - Phase 92',
        "description": 'Standard welfare program version 92 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-093',
        "name": 'National Livelihood Program - Phase 93',
        "description": 'Standard welfare program version 93 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-094',
        "name": 'National Livelihood Program - Phase 94',
        "description": 'Standard welfare program version 94 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-095',
        "name": 'National Livelihood Program - Phase 95',
        "description": 'Standard welfare program version 95 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-096',
        "name": 'National Livelihood Program - Phase 96',
        "description": 'Standard welfare program version 96 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-097',
        "name": 'National Livelihood Program - Phase 97',
        "description": 'Standard welfare program version 97 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-098',
        "name": 'National Livelihood Program - Phase 98',
        "description": 'Standard welfare program version 98 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-099',
        "name": 'National Livelihood Program - Phase 99',
        "description": 'Standard welfare program version 99 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-100',
        "name": 'National Livelihood Program - Phase 100',
        "description": 'Standard welfare program version 100 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-101',
        "name": 'National Livelihood Program - Phase 101',
        "description": 'Standard welfare program version 101 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-102',
        "name": 'National Livelihood Program - Phase 102',
        "description": 'Standard welfare program version 102 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-103',
        "name": 'National Livelihood Program - Phase 103',
        "description": 'Standard welfare program version 103 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-104',
        "name": 'National Livelihood Program - Phase 104',
        "description": 'Standard welfare program version 104 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-105',
        "name": 'National Livelihood Program - Phase 105',
        "description": 'Standard welfare program version 105 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-106',
        "name": 'National Livelihood Program - Phase 106',
        "description": 'Standard welfare program version 106 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-107',
        "name": 'National Livelihood Program - Phase 107',
        "description": 'Standard welfare program version 107 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-108',
        "name": 'National Livelihood Program - Phase 108',
        "description": 'Standard welfare program version 108 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-109',
        "name": 'National Livelihood Program - Phase 109',
        "description": 'Standard welfare program version 109 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-110',
        "name": 'National Livelihood Program - Phase 110',
        "description": 'Standard welfare program version 110 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-111',
        "name": 'National Livelihood Program - Phase 111',
        "description": 'Standard welfare program version 111 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-112',
        "name": 'National Livelihood Program - Phase 112',
        "description": 'Standard welfare program version 112 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-113',
        "name": 'National Livelihood Program - Phase 113',
        "description": 'Standard welfare program version 113 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-114',
        "name": 'National Livelihood Program - Phase 114',
        "description": 'Standard welfare program version 114 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-115',
        "name": 'National Livelihood Program - Phase 115',
        "description": 'Standard welfare program version 115 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-116',
        "name": 'National Livelihood Program - Phase 116',
        "description": 'Standard welfare program version 116 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-117',
        "name": 'National Livelihood Program - Phase 117',
        "description": 'Standard welfare program version 117 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-118',
        "name": 'National Livelihood Program - Phase 118',
        "description": 'Standard welfare program version 118 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-119',
        "name": 'National Livelihood Program - Phase 119',
        "description": 'Standard welfare program version 119 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Infrastructure',
    },
    {
        "scheme_id": 'GEN-SCHEME-120',
        "name": 'National Livelihood Program - Phase 120',
        "description": 'Standard welfare program version 120 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-121',
        "name": 'National Livelihood Program - Phase 121',
        "description": 'Standard welfare program version 121 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-122',
        "name": 'National Livelihood Program - Phase 122',
        "description": 'Standard welfare program version 122 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-123',
        "name": 'National Livelihood Program - Phase 123',
        "description": 'Standard welfare program version 123 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-124',
        "name": 'National Livelihood Program - Phase 124',
        "description": 'Standard welfare program version 124 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-125',
        "name": 'National Livelihood Program - Phase 125',
        "description": 'Standard welfare program version 125 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-126',
        "name": 'National Livelihood Program - Phase 126',
        "description": 'Standard welfare program version 126 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-127',
        "name": 'National Livelihood Program - Phase 127',
        "description": 'Standard welfare program version 127 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-128',
        "name": 'National Livelihood Program - Phase 128',
        "description": 'Standard welfare program version 128 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-129',
        "name": 'National Livelihood Program - Phase 129',
        "description": 'Standard welfare program version 129 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-130',
        "name": 'National Livelihood Program - Phase 130',
        "description": 'Standard welfare program version 130 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-131',
        "name": 'National Livelihood Program - Phase 131',
        "description": 'Standard welfare program version 131 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-132',
        "name": 'National Livelihood Program - Phase 132',
        "description": 'Standard welfare program version 132 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-133',
        "name": 'National Livelihood Program - Phase 133',
        "description": 'Standard welfare program version 133 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-134',
        "name": 'National Livelihood Program - Phase 134',
        "description": 'Standard welfare program version 134 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-135',
        "name": 'National Livelihood Program - Phase 135',
        "description": 'Standard welfare program version 135 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-136',
        "name": 'National Livelihood Program - Phase 136',
        "description": 'Standard welfare program version 136 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-137',
        "name": 'National Livelihood Program - Phase 137',
        "description": 'Standard welfare program version 137 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-138',
        "name": 'National Livelihood Program - Phase 138',
        "description": 'Standard welfare program version 138 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Healthcare',
    },
    {
        "scheme_id": 'GEN-SCHEME-139',
        "name": 'National Livelihood Program - Phase 139',
        "description": 'Standard welfare program version 139 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-140',
        "name": 'National Livelihood Program - Phase 140',
        "description": 'Standard welfare program version 140 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Finance',
    },
    {
        "scheme_id": 'GEN-SCHEME-141',
        "name": 'National Livelihood Program - Phase 141',
        "description": 'Standard welfare program version 141 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-142',
        "name": 'National Livelihood Program - Phase 142',
        "description": 'Standard welfare program version 142 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-143',
        "name": 'National Livelihood Program - Phase 143',
        "description": 'Standard welfare program version 143 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Agriculture',
    },
    {
        "scheme_id": 'GEN-SCHEME-144',
        "name": 'National Livelihood Program - Phase 144',
        "description": 'Standard welfare program version 144 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-145',
        "name": 'National Livelihood Program - Phase 145',
        "description": 'Standard welfare program version 145 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
    {
        "scheme_id": 'GEN-SCHEME-146',
        "name": 'National Livelihood Program - Phase 146',
        "description": 'Standard welfare program version 146 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-147',
        "name": 'National Livelihood Program - Phase 147',
        "description": 'Standard welfare program version 147 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-148',
        "name": 'National Livelihood Program - Phase 148',
        "description": 'Standard welfare program version 148 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Welfare',
    },
    {
        "scheme_id": 'GEN-SCHEME-149',
        "name": 'National Livelihood Program - Phase 149',
        "description": 'Standard welfare program version 149 for sustainable growth.',
        "eligibility_criteria": {},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Education',
    },
    {
        "scheme_id": 'GEN-SCHEME-150',
        "name": 'National Livelihood Program - Phase 150',
        "description": 'Standard welfare program version 150 for sustainable growth.',
        "eligibility_criteria": {'is_bpl_required': True},
        "benefits": 'Direct benefit transfer and logistical support.',
        "documents_required": ['Aadhaar Card', 'Identity Proof'],
"application_process": 'Visit [serviceonline.gov.in](https://serviceonline.gov.in/) or your local administrative/CSC office for application details.',
        "source": 'Government of India',
        "category": 'Employment',
    },
]



def _create_scheme(data: dict) -> Scheme:
    criteria_data = data.get("eligibility_criteria", {})
    criteria = EligibilityCriteria(**criteria_data)
    
    return Scheme(
        scheme_id=data["scheme_id"],
        name=data["name"],
        name_tamil=data.get("name_tamil"),
        description=data["description"],
        description_tamil=data.get("description_tamil"),
        eligibility_criteria=criteria,
        benefits=data["benefits"],
        benefits_tamil=data.get("benefits_tamil"),
        documents_required=data.get("documents_required", []),
        application_process=data.get("application_process", ""),
        source=data.get("source", "Government of India"),
        category=data.get("category", "General")
    )

schemes_data: List[Scheme] = [_create_scheme(s) for s in SCHEMES_DATA]

def get_all_schemes() -> List[Scheme]:
    return schemes_data

def get_scheme_by_id(scheme_id: str) -> Optional[Scheme]:
    for scheme in schemes_data:
        if scheme.scheme_id == scheme_id:
            return scheme
    return None

def get_schemes_by_category(category: str) -> List[Scheme]:
    return [s for s in schemes_data if s.category.lower() == category.lower()]

def search_schemes(query: str) -> List[Scheme]:
    query_lower = query.lower()
    results = []
    for scheme in schemes_data:
        if (query_lower in scheme.name.lower() or 
            query_lower in scheme.description.lower() or
            query_lower in scheme.category.lower()):
            results.append(scheme)
    return results
